adding frame_id information to depth controller node
itu-auv/auv-software pull request #61
Opened 2024-11-02 12:08 UTC by meydanoglu

1. Added a new field to `SetDepth.srv`: `frame_id`. This addition was necessary so that we could pass frame_id as a parameter to ros service. Ros service can now be called by;
`rosservice call /taluy/set_depth "target_depth: 5.0 frame_id: 'taluy/base_link/imu_link'"
`
2. Updated the function `targetdepthhandler` to take frame_id into account and transform the target_depth accordingly. The function now checks whether any frame_id is provided, and makes the appropriate transformation if we have one. If none, it passes the target depth directly.

_**Output of depth_controller_node, passed the above argument.**_

>  emin@emin  ~  rosrun auv_control depth_controller_node.py
[INFO] [1730549202.232636]: DepthControllerNode has started.
[INFO] [1730549202.348437]: Published cmd_pose with target depth: 0.0
[INFO] [1730549202.448895]: Published cmd_pose with target depth: 0.0
[INFO] [1730549202.548592]: Published cmd_pose with target depth: 0.0
[INFO] [1730549202.648865]: Published cmd_pose with target depth: 0.0
[INFO] [1730549203.548702]: Published cmd_pose with target depth: 0.0
[INFO] [1730549203.648719]: Published cmd_pose with target depth: 0.0
[INFO] [1730549203.748993]: Published cmd_pose with target depth: 0.0
[INFO] [1730549203.848313]: Published cmd_pose with target depth: 0.0
[INFO] [1730549203.948296]: Published cmd_pose with target depth: 0.0
[INFO] [1730549204.048224]: Published cmd_pose with target depth: 0.0
[INFO] [1730549204.148642]: Published cmd_pose with target depth: 0.0
[INFO] [1730549204.190259]: Received SetDepth request with target depth: 5.0 and frame_id: taluy/base_link/imu_link
[INFO] [1730549204.192819]: Transform from taluy/base_link/imu_link to taluy/base_link obtained successfully.
[INFO] [1730549204.194964]: Translation: x=-0.199, y=0.0, z=-0.0108
[INFO] [1730549204.197106]: Rotation: x=0.0, y=0.0, z=1.0, w=6.123233995736766e-17
[INFO] [1730549204.199998]: Target depth transformed to base frame: 4.9892
[INFO] [1730549204.248530]: Published cmd_pose with target depth: 4.9892
[INFO] [1730549204.348178]: Published cmd_pose with target depth: 4.9892
[INFO] [1730549205.749011]: Published cmd_pose with target depth: 4.9892
[INFO] [1730549205.848305]: Published cmd_pose with target depth: 4.9892
^C[INFO] [1730549205.948610]: Published cmd_pose with target depth: 4.9892

2024-11-02 16:44 UTC, senceryazici requested changes
Good work. thank you for the PR. 

The frame handling and transformations should be on the position controller side (the node that subscribes to cmd_pose.) This requires the cmd_pose type to be geometry_msgs/PoseStamped instead of geometry_msgs/Pose. then the header.frame_id will be interpreted same as your approach.

Adding frame_id to the SetDepth hence to the depth_controller_node is a good idea, with above implementation all you need to do in that node is

```py
def ..callback(req: SetDepthRequest):
    pose_stamped.header.frame_id = req.frame_id
    # continue publishing cmd_pose as usual.
```

2024-11-02 16:44 UTC, senceryazici commented on .gitignore
> +auv_simulation/
not necessary, or unrelated to this PR

2024-11-02 16:44 UTC, senceryazici commented on auv_control/auv_control/config/default.yaml
> +#kp: [0.0, 0.0, 1.5, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.1, 0.0, 1.0]
these are unrelated, please rollback them

2024-11-02 16:44 UTC, senceryazici commented on auv_control/auv_control/config/default.yaml
> +kp: [0.0, 0.0, 1.5, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 5.0, 0.0, 1.0]
these are unrelated, please rollback them

2024-11-06 17:02 UTC, meydanoglu commented
Hi, made some changes. Looking forward to hear from you @senceryazici

2024-11-08 15:02 UTC, senceryazici requested changes
Good work, we're getting there.

2024-11-08 20:02 UTC, meydanoglu commented on auv_control/auv_control/scripts/depth_controller_node.py
> +        self.target_frame_id = "taluy/base_link" # default to "taluy/base_link" if not set
True, controller_ros.h handles it already

2024-11-08 20:04 UTC, meydanoglu commented on auv_control/auv_control/scripts/depth_controller_node.py
> +        self.tf_listener = tf2_ros.TransformListener(self.tf_buffer)
Yes, transform handling is now at `controller_ros.h`

2024-11-08 20:07 UTC, meydanoglu commented on auv_control/auv_control/scripts/depth_controller_node.py
> +import tf2_geometry_msgs
TF libraries are no longer needed here. Also, time was not being used, thus removed as well.

2024-11-09 11:56 UTC, meydanoglu commented on auv_control/auv_control/include/auv_control/controller_ros.h
> +
Hmm. In this implementation,
`const auto is_transform_required = !source_frame.empty() || source_frame == base_frame;`
the transformation would be considered required even if source_frame is the same as default frame. But transforming to the same frame seems unnecessary. Do we need to transform the source frame to the default frame if they are the exact same?
This one will not cause unnecessary transformation:
`const auto is_transform_required = !source_frame.empty() && source_frame != default_frame; // only transform if not empty and not the same as default frame`

2024-11-09 12:06 UTC, meydanoglu commented on auv_control/auv_control/include/auv_control/controller_ros.h
> +        transformed_pose = msg->pose;
Hmm, never thought about that. 
```
catch (tf2::TransformException &ex) { // if transformation failed, ignore the target pose.
        return;
```

2024-11-09 13:03 UTC, meydanoglu commented on auv_control/auv_control/scripts/depth_controller_node.py
> +        if not req.frame_id:
Got it. 
`self.target_frame_id = req.frame_id  # If the target frame_id is not given, simply empty the frame_id`

2024-11-09 13:04 UTC, meydanoglu commented on auv_control/auv_control/include/auv_control/controller_ros.h
> +            ROS_DEBUG_STREAM_THROTTLE(10.0, "Using original pose (no transformation needed)");
Changing` base_frame` ---> `default_frame`

2024-11-09 15:08 UTC, senceryazici commented on auv_control/auv_control/include/auv_control/controller_ros.h
> +      const auto is_transform_required =
```cpp
const std::optional<std::string> get_source_frame(const std::string& source_frame) {
    if (source_frame.empty()) {
        return std::nullopt;
     } 

    if (source_frame == position_control_default_frame_) {
        return std::nullopt;
    }
    // transform is required.
    if (source_frame[0] == '/') {
        return source_frame.substr(1);
    }
    return source_frame;
}

void callback(.....) {
 // ...
const auto source_frame = get_source_frame(msg->header.frame_id);

auto transformed_pose = msg->pose;
if (source_frame.has_value()) {
    try {
        transformed_pose = ...(from=source_frame.value())...;
        tf2::doTransform....
     } catch ... {
       return;
     }
} 
}

 desired_state_.head(6) = auv::common::conversions::convert<
        geometry_msgs::Pose, ControllerBase::Vector>(transformed_pose);
    latest_command_time_ = ros::Time::now();

```


```

2024-11-11 08:56 UTC, meydanoglu commented on auv_control/auv_control/include/auv_control/controller_ros.h
> +    cmd_pose_sub_ = nh_.subscribe("cmd_pose_stamped", 1,
Alright. Changing the publishing part in depth_controller_node.py

```python
# Initialize publisher
        self.cmd_pose_pub = rospy.Publisher(
            "/taluy/cmd_pose", PoseStamped, queue_size=10)
```

2024-11-11 10:17 UTC, meydanoglu commented on auv_control/auv_control/include/auv_control/controller_ros.h
> +
New cmd_pose_callback structure with a get_source_frame helper function.

2024-11-11 10:17 UTC, meydanoglu commented on auv_control/auv_control/include/auv_control/controller_ros.h
> +  std::string position_control_default_frame_;
member variable decleration for ` position_control_default_frame_`

2024-11-11 10:17 UTC, meydanoglu commented on auv_control/auv_control/scripts/depth_controller_node.py
> +            "/taluy/cmd_pose", PoseStamped, queue_size=10)
publishes to `cmd_pose` instead of `cmd_pose_stamped`

2024-11-13 00:27 UTC, meydanoglu reviewed
Sure. Here is a video of me testing the new code:



https://github.com/user-attachments/assets/a3874903-e829-42d1-8090-d3a19f63f67f

> What is happening here?
1. I call the service without any tf, and the code fails to transform (nothing passed to `desired_state_`)
2. I define tf's and watch the `transformed_pose` change.
3. I kill the tf, and function now fails to transform again. (since there is no valid transform now.)


### Fix for a potential bug
We used to use `ros::Time(0)` for the transformation time. But this might lead to some unwanted problems, for example;

"_Maybe there existed a transformation between `frame_1` and `default_frame` 10 minutes ago. We received a service call with a `target_pose` in `frame_1` (maybe not likely, but still). Even though there's currently no transformation between these frames and we are absolutely not sure the last known transform is still valid, our code would have gone ahead and transformed the pose anyway. Now, that won't happen thanks to `ros::Time::now()` using the time of the function callback._"

2024-11-19 16:31 UTC, senceryazici commented
Looks good, I'm curious about the hardware tests though.

2024-11-19 17:47 UTC, meydanoglu commented
> Looks good, I'm curious about the hardware tests though.
We will be testing the features of the new implementation in the next pool test.

2025-01-17 20:42 UTC, eminmeydanoglu commented
In the last pool test, we successfully validated the frame-aware depth control functionality. Its only that my frame aware controller had an interesting interaction with @talhabw 's heading control implementation. Since my code was transforming everything in command pose, it also transformed the last three components, causing the heading control to request alignment with depth control's reference frame. So, I modified the transform handling process to only transform the z axis pose. The depth control now correctly responds to frame-specific commands while not causing heading control to go silly.


Irrelevantly, I want to mention that the way we handle command timeout is not bug-free. In this PR, notice how we avoid updating the desired state if there is a problem
```cpp
void cmd_pose_callback(const geometry_msgs::PoseStamped::ConstPtr& msg) {
         ..... 
         try {
         //transform z
      } catch (tf2::TransformException& ex) { // If unsuccessful, exit and don't update desired state
        ROS_DEBUG("Failed to transform pose");
        return;

```
So if the source frame is missing, we dont update the desired state (which is correct). But guess what, the desired state will stay the same with the last update unless there comes a new service call. So if the frame is gone missing after it was used even once, that desired state update will be kept forever. For more information about the issue refer to https://github.com/itu-auv/auv-software/issues/115

2025-01-28 17:38 UTC, eminmeydanoglu commented
This PR was thoroughly tested during the last pool test, including edge cases and its interaction with heading control, and everything worked flawlessly. I believe it’s ready to go! @senceryazici

2025-02-17 12:00 UTC, senceryazici submitted a review, later dismissed

2025-02-17 13:35 UTC, eminmeydanoglu commented
Hey @senceryazici, thanks for approving the PR. I want to share some thoughts on the current design, as I find it not so much cool:
The structure is,
depth_controller_node -> publish z pose value in reference frame -> controller_ros.h -> transform to odom frame -> write to desired_state matrix.  

1. Confusing cmd_pose values: This means the values in the cmd_pose message are not (always) in odom frame. cmd_pose.position.z = -0.5 might not mean that robot wants to go down 0.5 meters from water level--maybe something entirely different once transformed. This can be confusing and misleading for someone checking the cmd_pose commands. And it’s not immediately clear what the actual pose.z in the odom frame is (or should we print the desired state matrix :D)
2. SoC: Seems to me like processing the desired depth is a more of a "depth controller node" job. After all, it is responsible for deciding where we want to go depth-wise. I think controller_ros.h shouldn't be responsible of that? 

So I think it is more convenient to move the transformation part back to depth controller node. I am curious about your thoughts!

2025-02-25 16:50 UTC, ozanhakantunca approved these changes

2025-02-27 14:01 UTC, merged