WIP: add auv sim
itu-auv/auv-software pull request #94
Opened 2024-12-11 16:32 UTC by talhabw

2024-12-11 16:37 UTC, senceryazici requested changes

2024-12-11 16:37 UTC, senceryazici commented on auv_description/auv_common_descriptions/urdf/sensors/bar30.urdf.xacro
> +    <joint name="${name}_joint" type="revolute">
This needs to be fixed back in, you may add additional frame and a joint which is revolute.

2024-12-11 16:37 UTC, senceryazici commented on auv_description/auv_common_descriptions/urdf/sensors/bar30.urdf.xacro
> +      <limit upper="0" lower="0" effort="0" velocity="0" />
and this needs to be removed

2024-12-11 16:37 UTC, senceryazici commented on auv_description/auv_common_descriptions/urdf/sensors/xsens_mti_g710.urdf.xacro
> +    <joint name="${name}_joint" type="revolute">
same here

2024-12-11 16:37 UTC, senceryazici commented on auv_description/auv_common_descriptions/urdf/sensors/xsens_mti_g710.urdf.xacro
> +      <limit upper="0" lower="0" effort="0" velocity="0" />
same here

2024-12-15 22:34 UTC, senceryazici commented
Lets somehow not launch the gazebo client (UI app) if the use_gui is set to false. In other words, setting this to false should not launch any UI application and run everything without the need of a display. 


This will be useful for running the simulation to evaluate the robot’s performance programmatically without requiring a display, allowing it to be executed in GitHub Actions CI. (Spoiler alert :D)

2024-12-20 15:46 UTC, senceryazici commented
This PR is getting too big to handle. Let's narrow the context down  to the largest stable scope?

2024-12-27 23:07 UTC, senceryazici commented
CI is succeeding as expected now, let's proceed with clearing up this PR for the holy merge. @itu-auv/software

2024-12-27 23:10 UTC, senceryazici commented
That being said; merge, open or progress on your PR's that you think needs to be merged in before, to make this a stable PR. Perhaps [PR-110](https://github.com/itu-auv/auv-software/pull/110) @itu-auv/software

2024-12-27 23:13 UTC, senceryazici commented
Adding `needs simulation test` just for fun.

2025-01-13 09:47 UTC, talhabw commented
The simulation is working as it should in this version, there are still areas to improve, and we will look into them with time. I think we can merge this into main right now.

Here is a video of me testing the smach in simulation, the low rtf is caused by running the vision model on cpu, we also detect the red buoy too late because vision model works too slow on my cpu. Everything works as it should on a computer with gpu.

https://github.com/user-attachments/assets/1c34f337-d4dd-4215-8c9e-801098c19a7c

We also hardware tested this branch and couldn't find any problems.

2025-01-14 09:36 UTC, senceryazici approved these changes
For the sake of getting this merged in, I'll skip the code quality reviews. If it's working on robot and the sim, I'm fine with merging this in.

2025-01-14 09:44 UTC, merged