Update joy function
itu-auv/auv-software pull request #95
Opened 2024-12-14 11:22 UTC by ozanhakantunca

The previous _joy_manager.py_ file was configured for an Xbox controller, which caused it to perform incorrect functions. It has been updated to work with the joystick used during testing.

2024-12-14 17:56 UTC, senceryazici requested changes

2024-12-14 17:56 UTC, senceryazici commented on auv_teleop/scripts/joy_manager.py
> +            self.torpedo1_button_event.update(self.joy_data.buttons[4])
Looks good, but I'm going to be annoying for the next 5 minutes :D 

why not make these ros param? for example


```yaml
buttons:
  launch_torpedo1: 5
  launch_torpedo2: 3
  drop_ball: 2


axes:
  surge:  # (forward)
    index: 1 # button index
    gain: 0.1 # scalar
  sway: # lateral
    index: 2
    gain : 0.5
  yaw:
    index: 3 
    gain: 0.7


```

2024-12-14 18:00 UTC, senceryazici commented
then you can load different config files for different joysticks

```xml

  ...
  <rosparam command="load" file="$(find auv_teleop)/config/psp4.yaml"/>
  ...
```

2024-12-15 06:13 UTC, ozanhakantunca commented
Yes, that makes sense; it’s a much better solution. I’ll be working on it. :)

2024-12-15 22:26 UTC, senceryazici commented
Btw hardware test of this PR could be as simple as observing the cmd_vel output with the joystick. There is no need to test this with vehicle in pool.

2024-12-16 12:29 UTC, ozanhakantunca commented
Should I remove the README.md file in the package. Is it neccessary ? @senceryazici

2024-12-16 12:29 UTC, senceryazici approved these changes
Good work, this can be merged if tested.

2024-12-16 12:29 UTC, senceryazici commented on auv_teleop/config/psp4.yaml
> +buttons:
Isn't it PS4? :D

2024-12-16 12:39 UTC, merged